[package]
name = "prover-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
base.workspace = true
alloy = { workspace = true }
libflate = "2.1.0"

