[package]
name = "download-scroll-batch"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
scroll-verifier.workspace = true
scroll-executor.workspace = true
prover-types.workspace = true
clients.workspace = true
hex.workspace = true
serde_json.workspace = true
tokio = { version = "1.0", features = ["full"] }
base.workspace = true
env_logger.workspace = true