[package]
name = "linea-shomei"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
log.workspace = true
linea-zktrie.workspace = true
alloy.workspace = true
clients.workspace = true
