[package]
name = "base"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
log.workspace = true
chrono = "0.4.38"
async-trait.workspace = true

tokio = { version = "1.0", features = ["rt-multi-thread", "sync"] }