[package]
name = "sgx-prover"
version.workspace = true
edition.workspace = true
default-run = "sgx-prover"

[features]
tstd_app = ["automata-sgx-sdk/tstd_app"]

[package.metadata.sgx]
prover = { path = "../../crates/prover", config = "sgx/config.xml", edl = "sgx/prover.edl", lds = "sgx/enclave.lds", key = "sgx/private.pem", env = ["PKG_CONFIG_ALLOW_CROSS=1"] }

[dependencies]
serde.workspace = true
serde_json.workspace = true
automata-sgx-sdk.workspace = true

[build-dependencies]
automata-build-script.workspace = true