[package]
name = "sgx-prover"
version.workspace = true
edition.workspace = true

[package.metadata.sgx]
prover = { path = "../../crates/prover", config = "sgx/config.xml", edl = "sgx/prover.edl", lds = "sgx/enclave.lds", key = "sgx/private.pem", env = ["PKG_CONFIG_ALLOW_CROSS=1"] }

[dependencies]
serde.workspace = true
serde_json.workspace = true
automata-sgx-builder = { workspace = true, features = ["dcap", "app"] }

[build-dependencies]
automata-sgx-builder = { workspace = true, features = ["builder"] }